"""
Service: UX Audit
=================
Multimodal UX audit via two input modes:

  1. URL     — Scrape public page text with httpx/BeautifulSoup, run LLM audit.
  2. Image   — Accept a UI screenshot, use Groq vision (Llama-4 Scout) to audit.

Both modes apply a Reflexion loop:
  a. Initial audit generated by the primary LLM.
  b. Critic LLM checks coverage against a WCAG 2.2 checklist.
  c. Tavily search fetches targeted WCAG reference material for any gaps.
  d. Revision LLM produces the final, complete audit incorporating the gaps.
"""

import base64
import json

import httpx
from bs4 import BeautifulSoup
from fastapi import APIRouter, File, Form, UploadFile
from langchain_core.messages import AIMessage, HumanMessage
from langchain_groq import ChatGroq
from pydantic import BaseModel

from app import state
from app.config import GROQ_API_KEY
from app.services.chat import ChatResponse

router = APIRouter()

_MAX_SCRAPE_CHARS         = 12_000
_SCRAPE_TIMEOUT           = 12
_ALLOWED_IMAGE_EXTENSIONS = {"png", "jpg", "jpeg", "webp", "gif"}
_MAX_IMAGE_BYTES          = 10 * 1024 * 1024   # 10 MB

# ── Prompt ────────────────────────────────────────────────────────────────────
_UX_AUDIT_PROMPT = """Perform a thorough UX and accessibility audit.
Structure your entire response as Markdown with EXACTLY these ## headings, in this order:

## Summary
2–3 sentences summarising overall UX quality and the most important finding.

## Visual Hierarchy
Bullet list. Use ❌ for critical issues, ⚠️ for warnings, ✅ for positives.

## Accessibility
Bullet list. Cover WCAG failures, colour contrast, alt text, keyboard nav, ARIA.

## Navigation & Information Architecture
Bullet list. Evaluate menus, labelling, breadcrumbs, wayfinding.

## CTAs & Conversion
Bullet list. Assess button clarity, placement, copy, friction points.

## Typography & Readability
Bullet list. Font size, line length, contrast, heading hierarchy.

## Quick Wins
Numbered list of 3–5 highest-impact improvements, specific and actionable.

Rules:
- Use ONLY bullet / numbered lists inside sections (no prose paragraphs except Summary).
- Do NOT add any text before the first ## heading.
- Do NOT add headings other than those listed above.
- Bold (**text**) critical terms for emphasis.
"""

_UX_CRITIQUE_CHECKLIST = (
    "- Colour contrast ratios (WCAG AA: 4.5:1 text, 3:1 UI components)\n"
    "- Keyboard navigation and visible focus indicators\n"
    "- ARIA roles, labels, and landmark regions\n"
    "- Alt text for all images and icon-only buttons\n"
    "- Touch target sizes (minimum 44×44 px on mobile)\n"
    "- Form labels, inline error messages, and validation feedback\n"
    "- Heading hierarchy (h1→h2→h3, no skipped levels)\n"
    "- Descriptive link text (no 'click here' / 'read more')\n"
    "- Motion and animation safety (prefers-reduced-motion)\n"
    "- Screen reader reading order and semantic HTML"
)


# ── Reflexion refinement ──────────────────────────────────────────────────────

async def _refine_ux_audit(initial_audit: str) -> str:
    """Reflexion + optional Tavily refinement loop for a UX audit report."""
    if state.llm_quick is None:
        return initial_audit

    # Step 1: Critique
    critique_prompt = (
        "You are a WCAG 2.2 expert reviewer.\n\n"
        "Review the UX audit below and identify coverage gaps. "
        "Check specifically whether ALL of these areas were addressed:\n"
        f"{_UX_CRITIQUE_CHECKLIST}\n\n"
        "For each gap, write: Missing: <area> — <specific WCAG 2.2 criterion>\n\n"
        "If all areas are adequately covered, write only: COMPLETE\n\n"
        f"UX Audit to review:\n{initial_audit}"
    )
    critique_response = await state.llm_quick.ainvoke(critique_prompt)
    critique = str(critique_response.content).strip()

    if critique.upper().startswith("COMPLETE"):
        return initial_audit

    # Step 2: Tavily search for WCAG guidance
    gap_topics = [
        line.replace("Missing:", "").split("—")[0].strip()
        for line in critique.splitlines()
        if line.strip().lower().startswith("missing:")
    ]

    wcag_context = "(no additional reference material retrieved)"
    if state.tavily_client and gap_topics:
        search_query = "WCAG 2.2 " + " and ".join(gap_topics[:2])
        try:
            results = state.tavily_client.search(
                search_query, max_results=3, search_depth="basic",
                include_domains=["w3.org", "webaim.org", "developer.mozilla.org"],
            )
            snippets = [r.get("content", "")[:400] for r in results.get("results", []) if r.get("content")]
            if snippets:
                wcag_context = "\n\n".join(snippets)
        except Exception:
            pass

    # Step 3: Revised audit
    revision_prompt = (
        f"{_UX_AUDIT_PROMPT}\n\n"
        "An initial audit was produced and reviewed by an expert critic. "
        "Produce the FINAL complete audit that:\n"
        "  - Retains all valid findings from the initial audit\n"
        "  - Adds specific bullets for each identified gap\n"
        "  - Uses the WCAG 2.2 reference material to make recommendations concrete\n"
        "  - Maintains the exact ## section structure\n\n"
        f"## Initial Audit\n{initial_audit}\n\n"
        f"## Gaps Identified by Reflexion Critic\n{critique}\n\n"
        f"## WCAG 2.2 Reference Material\n{wcag_context}\n\n"
        "Produce only the final revised audit below — no preamble:"
    )
    revised = await state.llm_quick.ainvoke(revision_prompt)
    return str(revised.content).strip()


# ── URL scraping helper ───────────────────────────────────────────────────────

def _scrape_url(url: str) -> str:
    """Fetch a URL and return structured HTML elements + CSS styles relevant to UX analysis."""
    response = httpx.get(
        url,
        headers={"User-Agent": "Mozilla/5.0 (compatible; BrixoAI/1.0)"},
        follow_redirects=True,
        timeout=_SCRAPE_TIMEOUT,
    )
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")

    # ── CSS styles ────────────────────────────────────────────────────────────
    css_blocks = []
    for style_tag in soup.find_all("style"):
        css_text = style_tag.get_text(strip=True)
        if css_text:
            css_blocks.append(css_text[:1000])

    inline_styles = []
    for el in soup.find_all(style=True):
        inline_styles.append(f'<{el.name} style="{el["style"]}">')

    # Remove script tags only
    for tag in soup(["script"]):
        tag.decompose()

    elements = []

    # Page title & meta description
    if soup.title:
        elements.append(f"<title>{soup.title.string}</title>")
    meta_desc = soup.find("meta", attrs={"name": "description"})
    if meta_desc:
        elements.append(f'<meta name="description" content="{meta_desc.get("content", "")}">')

    # Heading hierarchy (h1–h6)
    for tag in soup.find_all(["h1", "h2", "h3", "h4", "h5", "h6"]):
        elements.append(str(tag))

    # Navigation blocks
    for nav in soup.find_all("nav"):
        elements.append(str(nav))

    # Anchor links
    for a in soup.find_all("a", href=True):
        elements.append(str(a))

    # Buttons and input controls
    for el in soup.find_all(["button", "input", "select", "textarea"]):
        elements.append(str(el))

    # Forms
    for form in soup.find_all("form"):
        elements.append(str(form))

    # Images (alt text matters for accessibility)
    for img in soup.find_all("img"):
        elements.append(str(img))

    # ── Assemble output ───────────────────────────────────────────────────────
    sections = []
    if css_blocks:
        sections.append("=== STYLESHEET CSS ===\n" + "\n".join(css_blocks))
    if inline_styles:
        sections.append("=== INLINE STYLES ===\n" + "\n".join(inline_styles))
    sections.append("=== HTML ELEMENTS ===\n" + "\n".join(elements))

    return "\n\n".join(sections)[:_MAX_SCRAPE_CHARS]


# ── URL audit endpoint ────────────────────────────────────────────────────────

@router.post("/ux-audit/url", response_model=ChatResponse)
async def ux_audit_url(
    url: str = Form(...),
    message: str = Form("Perform a UX and accessibility audit of this page."),
    history: str = Form("[]"),
):
    """Scrape a public URL and run a structured UX audit."""
    if not url.startswith(("http://", "https://")):
        return ChatResponse(reply="Please provide a full URL starting with https:// 🔗")

    _hint = " Alternatively, upload a screenshot with the 📎 button — I can audit images too! 🖼️"

    try:
        page_text = _scrape_url(url)
    except httpx.TimeoutException:
        return ChatResponse(reply="That page took too long to load." + _hint)
    except httpx.HTTPStatusError as e:
        status = e.response.status_code
        reason = (
            "The site is blocking automated access (403 Forbidden)." if status == 403 else
            "That URL returned a 404 — the page doesn't exist." if status == 404 else
            f"The server returned an error ({status})."
        )
        return ChatResponse(reply=reason + _hint)
    except Exception:
        return ChatResponse(reply="I had trouble reaching that URL." + _hint)

    if len(page_text) < 100:
        return ChatResponse(reply="Not enough readable content — the page may be JavaScript-rendered or behind a login." + _hint)

    hist = json.loads(history)
    chat_history = [
        HumanMessage(content=m["content"]) if m["role"] == "user"
        else AIMessage(content=m["content"])
        for m in hist
    ]

    enhanced = f"{_UX_AUDIT_PROMPT}\n\n--- Scraped content from: {url} ---\n\n{page_text}"
    result = await state.chain.ainvoke({"input": enhanced, "chat_history": chat_history, "service_mode": "ux-audit"})
    refined_audit = await _refine_ux_audit(result["answer"])

    return ChatResponse(reply="Your UX audit is ready! The report is open in the panel. 🎨", audit_report=refined_audit)


# ── Image audit endpoint ──────────────────────────────────────────────────────

@router.post("/ux-audit/image", response_model=ChatResponse)
async def ux_audit_image(
    file: UploadFile = File(...),
    message: str = Form("Perform a UX and accessibility audit of this screenshot."),
    history: str = Form("[]"),
):
    """Accept a UI screenshot and return a vision-powered UX audit."""
    filename = file.filename or "screenshot"
    ext = filename.rsplit(".", 1)[-1].lower()

    if ext not in _ALLOWED_IMAGE_EXTENSIONS:
        return ChatResponse(reply="Please upload a PNG, JPG, WEBP, or GIF screenshot! 🖼️")

    contents = await file.read()
    if len(contents) > _MAX_IMAGE_BYTES:
        return ChatResponse(reply="That image is too large (max 10 MB). Please compress it and try again! 🖼️")

    mime = {"png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg", "webp": "image/webp", "gif": "image/gif"}.get(ext, "image/png")
    b64 = base64.b64encode(contents).decode()

    hist = json.loads(history)
    chat_history = [
        HumanMessage(content=m["content"]) if m["role"] == "user"
        else AIMessage(content=m["content"])
        for m in hist
    ]

    vision_llm = ChatGroq(
        api_key=GROQ_API_KEY,
        model="meta-llama/llama-4-scout-17b-16e-instruct",
        temperature=0.4,
        max_tokens=1500,
    )

    # Quick check: is this actually a UI screenshot?
    check_msg = HumanMessage(content=[
        {"type": "text",      "text": "Does this image show a website, web app, or software UI screenshot? Reply with only YES or NO."},
        {"type": "image_url", "image_url": {"url": f"data:{mime};base64,{b64}"}},
    ])
    check_resp = await vision_llm.ainvoke([check_msg])
    if not str(check_resp.content).strip().upper().startswith("YES"):
        return ChatResponse(reply="That doesn't look like a UI screenshot. Please upload a screenshot of a webpage or app! 🖼️")

    vision_msg = HumanMessage(content=[
        {"type": "text",      "text": _UX_AUDIT_PROMPT},
        {"type": "image_url", "image_url": {"url": f"data:{mime};base64,{b64}"}},
    ])
    response      = await vision_llm.ainvoke(chat_history + [vision_msg])
    refined_audit = await _refine_ux_audit(str(response.content))

    return ChatResponse(reply="Your UX audit is ready! The report is open in the panel. 🎨", audit_report=refined_audit)
